const LANGUAGES = [
  { label: "English", value: "en" },
  { label: "Spanish", value: "es" },
  { label: "Portuguese", value: "pt" },
  { label: "Indonesian", value: "id" },
  { label: "French", value: "fr" },
  { label: "Arabic", value: "ar" },
  { label: "Turkish", value: "tr" },
  { label: "Thai", value: "th" },
  { label: "Vietnamese", value: "vi" },
  { label: "German", value: "de" },
  { label: "Italian", value: "it" },
  { label: "Japanese", value: "ja" },
  { label: "Chinese Simplified", value: "zh-CN" },
  { label: "Chinese Traditional", value: "zh-TW" },
  { label: "Russian", value: "ru" },
  { label: "Korean", value: "ko" },
  { label: "Polish", value: "pl" },
  { label: "Dutch", value: "nl" },
  { label: "Romanian", value: "ro" },
  { label: "Hungarian", value: "hu" },
  { label: "Swedish", value: "sv" },
  { label: "Czech", value: "cs" },
  { label: "Hindi", value: "hi" },
  { label: "Bengali", value: "bn" },
  { label: "Danish", value: "da" },
  { label: "Farsi", value: "fa" },
  { label: "Filipino", value: "tl" },
  { label: "Finnish", value: "fi" },
  { label: "Hebrew", value: "he" },
  { label: "Malay", value: "ms" },
  { label: "Norwegian", value: "no" },
  { label: "Ukrainian", value: "uk" },
];
export default LANGUAGES;
